--
-- PostgreSQL database dump
--

-- Dumped from database version 13.15
-- Dumped by pg_dump version 16.3

-- Started on 2025-10-27 17:46:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 201 (class 1259 OID 32846)
-- Name: jogador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jogador (
    id bigint NOT NULL,
    nome character varying(255) NOT NULL,
    senha character varying(255)
);


ALTER TABLE public.jogador OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 32844)
-- Name: jogador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jogador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jogador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 32854)
-- Name: jogador_jogo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jogador_jogo (
    jogador_id bigint NOT NULL,
    jogo_id bigint NOT NULL
);


ALTER TABLE public.jogador_jogo OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 32859)
-- Name: jogo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jogo (
    id bigint NOT NULL,
    descricao character varying(255),
    imagem_url character varying(255),
    titulo character varying(255)
);


ALTER TABLE public.jogo OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 32857)
-- Name: jogo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jogo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jogo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2999 (class 0 OID 32846)
-- Dependencies: 201
-- Data for Name: jogador; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jogador (id, nome, senha) FROM stdin;
1	joaoaoaoa	12345678
\.


--
-- TOC entry 3000 (class 0 OID 32854)
-- Dependencies: 202
-- Data for Name: jogador_jogo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jogador_jogo (jogador_id, jogo_id) FROM stdin;
\.


--
-- TOC entry 3002 (class 0 OID 32859)
-- Dependencies: 204
-- Data for Name: jogo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jogo (id, descricao, imagem_url, titulo) FROM stdin;
1	Team Fortress 2 é um jogo eletrônico free-to-play multijogador de tiro em primeira pessoa desenvolvido pela Valve, baseado em equipes e com foco em combates. 	/covers/tf2.jpg	Team Fortress 2
3	Dead by Daylight é um jogo eletrônico multijogador online assimétrico do gênero survival horror desenvolvido pelo estúdio canadense Behaviour Interactive.	/covers/dbd.jpg	Dead By Daylight
2	Half-Life 2 é um jogo eletrônico de tiro em primeira pessoa de 2004, desenvolvido e publicado pela Valve Corporation.	/covers/hl2.jpg	Half-Life 2
4	Counter-Strike 2, conhecido também como CS2 é um jogo tático multijogador de tiro em primeira pessoa anunciado 22 de março de 2023 e lançado em 27 de setembro de 2023. 	/covers/cs2.jpg	Counter-Strike 2
\.


--
-- TOC entry 3009 (class 0 OID 0)
-- Dependencies: 200
-- Name: jogador_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jogador_id_seq', 1, true);


--
-- TOC entry 3010 (class 0 OID 0)
-- Dependencies: 203
-- Name: jogo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jogo_id_seq', 4, true);


--
-- TOC entry 2863 (class 2606 OID 32853)
-- Name: jogador jogador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jogador
    ADD CONSTRAINT jogador_pkey PRIMARY KEY (id);


--
-- TOC entry 2865 (class 2606 OID 32866)
-- Name: jogo jogo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jogo
    ADD CONSTRAINT jogo_pkey PRIMARY KEY (id);


--
-- TOC entry 2866 (class 2606 OID 32867)
-- Name: jogador_jogo fk5rwovmb3mu493xl96h0j336g7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jogador_jogo
    ADD CONSTRAINT fk5rwovmb3mu493xl96h0j336g7 FOREIGN KEY (jogo_id) REFERENCES public.jogo(id);


--
-- TOC entry 2867 (class 2606 OID 32872)
-- Name: jogador_jogo fkd4karmeoav6lmf1epknfs93gh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jogador_jogo
    ADD CONSTRAINT fkd4karmeoav6lmf1epknfs93gh FOREIGN KEY (jogador_id) REFERENCES public.jogador(id);


--
-- TOC entry 3008 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2025-10-27 17:46:57

--
-- PostgreSQL database dump complete
--

